(function(){
'use strict';
let stream=null,raf=0,detector=null,busy=false,scanCanvas=null,lastScan=0;
function toast(m){let x=document.getElementById('scQrToast');if(!x){x=document.createElement('div');x.id='scQrToast';x.style.cssText='position:fixed;left:50%;bottom:85px;transform:translateX(-50%);z-index:4000002;background:#102a43;color:white;padding:10px 14px;border-radius:12px;font:700 11px Arial;box-shadow:0 8px 28px #0005;max-width:86%;text-align:center';document.body.appendChild(x)}x.textContent=m;x.style.display='block';setTimeout(()=>x.style.display='none',2600)}
function route(text){try{let u=new URL(String(text||''));if(u.hostname!=='sursandconnect.github.io')throw 0;let t=u.searchParams.get('t'),id=u.searchParams.get('id');if(!t||!id)throw 0;let map={businesses:'businesses.html',business:'businesses.html',services:'services.html',service:'services.html',education:'education.html',healthcare:'healthcare.html',places:'important-places.html',place:'important-places.html',governmentOffices:'government-offices.html',government:'government-offices.html'};if(!map[t])throw 0;closeScanner();let prefix=location.pathname.includes('/p/')?'':'p/';let key=(t==='services'||t==='service')?'focus':'focusId';location.href=prefix+map[t]+'?'+key+'='+encodeURIComponent(id)}catch(e){toast('यह Sursand Connect का मान्य QR नहीं है।')}}
function closeScanner(){cancelAnimationFrame(raf);raf=0;busy=false;if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}document.getElementById('scQrScannerModal')?.remove()}
async function scanLoop(video,ts){if(!detector||!stream)return;if(lastScan&&ts-lastScan<100){raf=requestAnimationFrame(t=>scanLoop(video,t));return}lastScan=ts;try{if(video.readyState>=2&&!busy){busy=true;let a=await detector.detect(video);if((!a||!a[0])&&video.videoWidth&&video.videoHeight){const w=video.videoWidth,h=video.videoHeight,s=Math.floor(Math.min(w,h)*.8),x=Math.floor((w-s)/2),y=Math.floor((h-s)/2);scanCanvas=scanCanvas||document.createElement('canvas');scanCanvas.width=s;scanCanvas.height=s;scanCanvas.getContext('2d').drawImage(video,x,y,s,s,0,0,s,s);a=await detector.detect(scanCanvas)}busy=false;if(a&&a[0]&&a[0].rawValue){route(a[0].rawValue);return}}}catch(e){busy=false}raf=requestAnimationFrame(t=>scanLoop(video,t))}
function fileFallback(){let i=document.createElement('input');i.type='file';i.accept='image/*';i.onchange=async()=>{let f=i.files&&i.files[0];if(!f)return;if(!('BarcodeDetector'in window)){toast('इस ब्राउज़र में QR पढ़ने की सुविधा उपलब्ध नहीं है।');return}try{let b=await createImageBitmap(f),d=new BarcodeDetector({formats:['qr_code']}),a=await d.detect(b);if(a&&a[0])route(a[0].rawValue);else toast('QR नहीं मिला।')}catch(e){toast('QR पढ़ा नहीं जा सका।')}};i.click()}
async function openScanner(){closeScanner();if(!('BarcodeDetector'in window)||!navigator.mediaDevices?.getUserMedia){fileFallback();return}let m=document.createElement('div');m.id='scQrScannerModal';m.style.cssText='position:fixed;inset:0;background:#07111eeF;z-index:4000001;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:20px;color:white;font-family:Arial';m.innerHTML='<button id="scQrClose" style="position:absolute;right:18px;top:18px;width:44px;height:44px;border:0;border-radius:14px;background:#fff;color:#111;font-size:26px">×</button><div style="font-weight:900;font-size:18px;margin-bottom:14px">Scan Sursand Connect QR</div><div style="width:min(82vw,360px);aspect-ratio:1;border-radius:26px;overflow:hidden;position:relative;background:#000"><video id="scQrVideo" playsinline muted style="width:100%;height:100%;object-fit:cover"></video><div style="position:absolute;inset:18%;border:3px solid #fff;border-radius:24px;box-shadow:0 0 0 999px #0003"></div></div><div style="font-size:11px;opacity:.85;margin-top:14px">QR को फ्रेम के अंदर रखें</div><button id="scQrGallery" style="margin-top:15px;border:0;border-radius:14px;padding:11px 18px;font-weight:800">Gallery से QR चुनें</button>';
document.body.appendChild(m);m.querySelector('#scQrClose').onclick=closeScanner;m.querySelector('#scQrGallery').onclick=fileFallback;
try{detector=new BarcodeDetector({formats:['qr_code']});stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});let v=m.querySelector('#scQrVideo');v.srcObject=stream;await v.play();lastScan=0;raf=requestAnimationFrame(t=>scanLoop(v,t))}catch(e){closeScanner();fileFallback()}}
window.SCQR={openScanner,route,closeScanner};
})();
